### ISSUE TITLE
jQuery shouldn't have a capital letter J

### ISSUE THREAD

**Issue by wifelette** [learn-co-curriculum/js-and-the-world#4]
Seen here:
> Soon after the debut of Google Maps, programmers began trying to fix Javascript and developed tools like JQuery and Node.js. (We'll talk about JQuery later.)

**Comment by Donnadieu** [comment]
Hello,

We've merged this pull request in. Thank you for submitting this PR and for contributing to a learn-co-curriculum repository!

We appreciate your support! 💙
