### ISSUE TITLE
Lost materials 

### ISSUE THREAD

**Issue by heythere515** [learn-co-curriculum/js-and-the-world#6]
Hi my materials for the course have disappeared

**Comment by maxwellbenton** [comment]
Hi @heythere515,

Sorry to hear you're having trouble accessing the lessons in this course. If you are still unable to access the lessons, please reach out to support@learn.co for further assistance. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) is typically reserved for problems with the Learn.co curriculum content specific to this repository. While we do monitor repository issues, we are unable to provide support for problems related to the Learn platform.

If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thank you!
